name: CI Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run tests
        id: tests
        continue-on-error: true
        run: |
          mkdir -p artifacts
          echo "Running tests..."
          #./run_gh_tests.sh > artifacts/test.log 2>&1
          bash run_gh_tests.sh > artifacts/test.log 2>&1

      - name: Upload test artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test-output-ubuntu
          path: artifacts/

      - name: Fail if tests failed
        if: steps.tests.outcome == 'failure'
        run: exit 1

  test-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run tests
        id: tests
        continue-on-error: true
        run: |
          mkdir -p artifacts
          echo "Running tests..."
          #./run_gh_tests.sh > artifacts/test.log 2>&1
          bash run_gh_tests.sh > artifacts/test.log 2>&1

      - name: Upload test artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test-output-macos
          path: artifacts/

      - name: Fail if tests failed
        if: steps.tests.outcome == 'failure'
        run: exit 1

  test-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show shell info
        shell: bash
        run: |
          { echo "Sehll: $SHELL"
          uname -a
          which bash
          pwd
          ls -la } > artifacts/test_shell.txt 2>&1

      - name: Run tests
        id: tests
        shell: bash
        continue-on-error: true
        run: |
          mkdir -p artifacts
          echo "Running tests..."
          bash run_gh_tests.sh > artifacts/test.log 2>&1

      - name: Upload test artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test-output-windows
          path: artifacts/

      - name: Fail if tests failed
        if: steps.tests.outcome == 'failure'
        run: exit 1

