name: CI Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-ubuntu:
    runs-on: ubuntu-latest

    steps:
      #- name: Checkout
      #  uses: actions/checkout@v4

      - name: Clone to compare directory
        run: |
          git clone https://github.com/${{ github.repository }} ./R1
          git clone --bare https://github.com/${{ github.repository }} ./bare1.git
          

      - name: Run tests
        id: tests
        continue-on-error: true
        run: |
          PATH=$PATH:$PWD
          mkdir -p git-issue-test
          mkdir -p git-issue-test/artifacts
          echo "Running tests..."
          cd git-issue-test
          #./run_gh_tests.sh > artifacts/test.log 2>&1
          bash -x ../run_test_issues.sh > artifacts/run_test_issues.log 2>&1

      - name: Upload test artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test-output-ubuntu
          path: artifacts/

      - name: Fail if tests failed
        if: steps.tests.outcome == 'failure'
        run: exit 1

  test-macos:
    runs-on: macos-latest

    steps:
      #- name: Checkout
      #  uses: actions/checkout@v4

      - name: Clone to compare directory
        run: |
          git clone https://github.com/${{ github.repository }} ./R1
          git clone --bare https://github.com/${{ github.repository }} ./bare1.git

      - name: Run tests
        id: tests
        continue-on-error: true
        run: |
          PATH=$PATH:$PWD
          mkdir -p git-issue-test
          mkdir -p git-issue-test/artifacts
          echo "Running tests..."
          cd git-issue-test
          #./run_gh_tests.sh > artifacts/test.log 2>&1
          bash -x ../run_test_issues.sh > artifacts/run_test_issues.log 2>&1

      - name: Upload test artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test-output-macos
          path: artifacts/

      - name: Fail if tests failed
        if: steps.tests.outcome == 'failure'
        run: exit 1

  test-windows:
    runs-on: windows-latest

    steps:
      #- name: Checkout
      #  uses: actions/checkout@v4

      - name: Clone to compare directory
        run: |
          git clone https://github.com/${{ github.repository }} ./R1
          git clone --bare https://github.com/${{ github.repository }} ./bare1.git

      - name: Show shell info
        shell: bash
        run: |
          mkdir -p artifacts
          { 
            echo "Shell: $SHELL"
            uname -a
            which bash
            pwd
            ls -la 
          } > artifacts/test_shell.txt 2>&1

      - name: Run tests
        id: tests
        shell: bash
        continue-on-error: true
        run: |
          PATH=$PATH:$PWD
          mkdir -p git-issue-test
          mkdir -p git-issue-test/artifacts
          echo "Running tests..."
          cd git-issue-test
          #./run_gh_tests.sh > artifacts/test.log 2>&1
          bash -x ../run_test_issues.sh > artifacts/run_test_issues.log 2>&1

      - name: Upload test artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test-output-windows
          path: artifacts/

      - name: Fail if tests failed
        if: steps.tests.outcome == 'failure'
        run: exit 1

